# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lkoekoek\Documents\maya\2019\scripts\rsExportUi.ui',
# licensing of 'C:\Users\lkoekoek\Documents\maya\2019\scripts\rsExportUi.ui' applies.
#
# Created: Mon Sep  2 23:03:26 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 950)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(520, 950))
        Form.setMaximumSize(QtCore.QSize(520, 950))
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 531, 941))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(26, 26, 470, 887))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_asset_folder_path = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_asset_folder_path.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_asset_folder_path.setFont(font)
        self.label_asset_folder_path.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_asset_folder_path)
        self.folder_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.folder_status.setFont(font)
        self.folder_status.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.folder_status.setObjectName("folder_status")
        self.horizontalLayout_3.addWidget(self.folder_status)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.asset_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.asset_path.setMinimumSize(QtCore.QSize(0, 30))
        self.asset_path.setObjectName("asset_path")
        self.horizontalLayout_2.addWidget(self.asset_path)
        self.browse_asset_path = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.browse_asset_path.setMinimumSize(QtCore.QSize(150, 30))
        self.browse_asset_path.setObjectName("btn_browse")
        self.horizontalLayout_2.addWidget(self.browse_asset_path)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_scene_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_scene_name.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_scene_name)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, 100, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.scene_name_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.scene_name_input.sizePolicy().hasHeightForWidth())
        self.scene_name_input.setSizePolicy(sizePolicy)
        self.scene_name_input.setMinimumSize(QtCore.QSize(50, 30))
        self.scene_name_input.setObjectName("scene_name_input")
        self.horizontalLayout_14.addWidget(self.scene_name_input)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 5, 200, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radio_export_all = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_export_all.setObjectName("radio_export_all")
        self.export_options_group = QtWidgets.QButtonGroup(Form)
        self.export_options_group.setObjectName("export_options_group")
        self.export_options_group.addButton(self.radio_export_all)
        self.gridLayout_2.addWidget(self.radio_export_all, 0, 0, 1, 1)
        self.radio_export_sel = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_export_sel.setObjectName("radio_export_sel")
        self.export_options_group.addButton(self.radio_export_sel)
        self.gridLayout_2.addWidget(self.radio_export_sel, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 5, -1, 15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.check_export_animation = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_export_animation.setObjectName("check_export_animation")
        self.verticalLayout_4.addWidget(self.check_export_animation)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(30)
        self.horizontalLayout_6.setContentsMargins(-1, -1, 200, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.anim_range_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.anim_range_label.setMinimumSize(QtCore.QSize(120, 0))
        self.anim_range_label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.anim_range_label)
        self.anim_range_min = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.anim_range_min.setMinimumSize(QtCore.QSize(0, 25))
        self.anim_range_min.setMinimum(-999999)
        self.anim_range_min.setMaximum(999999)
        self.anim_range_min.setObjectName("anim_range_min")
        self.horizontalLayout_6.addWidget(self.anim_range_min)
        self.anim_range_max = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.anim_range_max.setMinimumSize(QtCore.QSize(0, 25))
        self.anim_range_max.setMinimum(-999999)
        self.anim_range_max.setMaximum(999999)
        self.anim_range_max.setObjectName("anim_range_max")
        self.horizontalLayout_6.addWidget(self.anim_range_max)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.check_copy_textures = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_copy_textures.setObjectName("check_copy_textures")
        self.verticalLayout_5.addWidget(self.check_copy_textures)
        self.keep_mat_paths = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.keep_mat_paths.setObjectName("check_update_mat_paths")
        self.verticalLayout_5.addWidget(self.keep_mat_paths)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_export_scene_as = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_export_scene_as.setMinimumSize(QtCore.QSize(0, 25))
        self.label_export_scene_as.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_export_scene_as)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 200, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.radio_export_ptcloud = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_export_ptcloud.setObjectName("radio_export_ptcloud")
        self.point_cloud_group = QtWidgets.QButtonGroup(Form)
        self.point_cloud_group.setObjectName("point_cloud_group")
        self.point_cloud_group.addButton(self.radio_export_ptcloud)
        self.gridLayout.addWidget(self.radio_export_ptcloud, 0, 0, 1, 1)
        self.radio_export_fbx = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_export_fbx.setObjectName("radio_export_fbx")
        self.point_cloud_group.addButton(self.radio_export_fbx)
        self.gridLayout.addWidget(self.radio_export_fbx, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.check_extra_ptcloud = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_extra_ptcloud.setObjectName("check_extra_ptcloud")
        self.verticalLayout_7.addWidget(self.check_extra_ptcloud)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.check_extra_occlusion = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_extra_occlusion.setMinimumSize(QtCore.QSize(250, 0))
        self.check_extra_occlusion.setObjectName("check_extra_culling")
        self.horizontalLayout_9.addWidget(self.check_extra_occlusion)
        self.active_camera_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.active_camera_label.setMaximumSize(QtCore.QSize(90, 16777215))
        self.active_camera_label.setObjectName("active_camera_label")
        self.horizontalLayout_9.addWidget(self.active_camera_label)
        self.active_camera = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.active_camera.setMinimumSize(QtCore.QSize(0, 30))
        self.active_camera.setObjectName("active_camera")
        self.horizontalLayout_9.addWidget(self.active_camera)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.check_extra_lights = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_extra_lights.setObjectName("check_extra_lights")
        self.verticalLayout_7.addWidget(self.check_extra_lights)
        self.check_extra_special_mats = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_extra_special_mats.setMinimumSize(QtCore.QSize(0, 30))
        self.check_extra_special_mats.setObjectName("check_extra_special_mats")
        self.verticalLayout_7.addWidget(self.check_extra_special_mats)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 5, 150, 10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.check_skybox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_skybox.setObjectName("check_skybox")
        self.horizontalLayout_10.addWidget(self.check_skybox)
        self.check_skybox_radiance = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_skybox_radiance.setObjectName("check_skybox_radiance")
        self.horizontalLayout_10.addWidget(self.check_skybox_radiance)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.skybox_envpath_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.skybox_envpath_label.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.skybox_envpath_label)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.textbox_skybox_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.textbox_skybox_path.setMinimumSize(QtCore.QSize(0, 30))
        self.textbox_skybox_path.setObjectName("textbox_skybox_path")
        self.horizontalLayout_11.addWidget(self.textbox_skybox_path)
        self.skybox_browse = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.skybox_browse.setMinimumSize(QtCore.QSize(150, 30))
        self.skybox_browse.setObjectName("skybox_browse")
        self.horizontalLayout_11.addWidget(self.skybox_browse)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.skybox_radiance_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.skybox_radiance_label.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.skybox_radiance_label)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.textbox_radiance_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.textbox_radiance_path.setEnabled(False)
        self.textbox_radiance_path.setMinimumSize(QtCore.QSize(0, 30))
        self.textbox_radiance_path.setObjectName("textbox_radiance_path")
        self.horizontalLayout_12.addWidget(self.textbox_radiance_path)
        self.radiance_browse = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.radiance_browse.setEnabled(False)
        self.radiance_browse.setMinimumSize(QtCore.QSize(150, 30))
        self.radiance_browse.setObjectName("radiance_browse")
        self.horizontalLayout_12.addWidget(self.radiance_browse)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.skybox_irradiance_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.skybox_irradiance_label.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.skybox_irradiance_label)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.textbox_irradiance_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.textbox_irradiance_path.setEnabled(False)
        self.textbox_irradiance_path.setMinimumSize(QtCore.QSize(0, 30))
        self.textbox_irradiance_path.setObjectName("textbox_irradiance_path")
        self.horizontalLayout_13.addWidget(self.textbox_irradiance_path)
        self.irradiance_browse = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.irradiance_browse.setEnabled(False)
        self.irradiance_browse.setMinimumSize(QtCore.QSize(150, 30))
        self.irradiance_browse.setObjectName("irradiance_browse")
        self.horizontalLayout_13.addWidget(self.irradiance_browse)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_8)
        self.btn_export = QtWidgets.QPushButton(self.tab_2)
        self.btn_export.setGeometry(QtCore.QRect(-15, 842, 541, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_export.sizePolicy().hasHeightForWidth())
        self.btn_export.setSizePolicy(sizePolicy)
        self.btn_export.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.btn_export.setFont(font)
        self.btn_export.setObjectName("btn_export")
        self.tabWidget.addTab(self.tab_2, "")
        self.log_tab = QtWidgets.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.text_log = QtWidgets.QPlainTextEdit(self.log_tab)
        self.text_log.setGeometry(QtCore.QRect(20, 20, 481, 801))
        self.text_log.setObjectName("text_log")
        self.clear_log = QtWidgets.QPushButton(self.log_tab)
        self.clear_log.setGeometry(QtCore.QRect(-4, 857, 531, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_log.sizePolicy().hasHeightForWidth())
        self.clear_log.setSizePolicy(sizePolicy)
        self.clear_log.setMinimumSize(QtCore.QSize(0, 50))
        self.clear_log.setObjectName("clear_log")
        self.tabWidget.addTab(self.log_tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.about_text = QtWidgets.QLabel(self.tab_4)
        self.about_text.setGeometry(QtCore.QRect(20, 20, 491, 291))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.about_text.setFont(font)
        self.about_text.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.about_text.setObjectName("about_text")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget, self.asset_path)
        Form.setTabOrder(self.asset_path, self.browse_asset_path)
        Form.setTabOrder(self.browse_asset_path, self.scene_name_input)
        Form.setTabOrder(self.scene_name_input, self.radio_export_all)
        Form.setTabOrder(self.radio_export_all, self.radio_export_sel)
        Form.setTabOrder(self.radio_export_sel, self.check_export_animation)
        Form.setTabOrder(self.check_export_animation, self.anim_range_min)
        Form.setTabOrder(self.anim_range_min, self.anim_range_max)
        Form.setTabOrder(self.anim_range_max, self.check_copy_textures)
        Form.setTabOrder(self.check_copy_textures, self.keep_mat_paths)
        Form.setTabOrder(self.keep_mat_paths, self.radio_export_ptcloud)
        Form.setTabOrder(self.radio_export_ptcloud, self.radio_export_fbx)
        Form.setTabOrder(self.radio_export_fbx, self.check_extra_ptcloud)
        Form.setTabOrder(self.check_extra_ptcloud, self.check_extra_occlusion)
        Form.setTabOrder(self.check_extra_occlusion, self.active_camera)
        Form.setTabOrder(self.active_camera, self.check_extra_lights)
        Form.setTabOrder(self.check_extra_lights, self.check_extra_special_mats)
        Form.setTabOrder(self.check_extra_special_mats, self.check_skybox)
        Form.setTabOrder(self.check_skybox, self.check_skybox_radiance)
        Form.setTabOrder(self.check_skybox_radiance, self.textbox_skybox_path)
        Form.setTabOrder(self.textbox_skybox_path, self.skybox_browse)
        Form.setTabOrder(self.skybox_browse, self.textbox_radiance_path)
        Form.setTabOrder(self.textbox_radiance_path, self.radiance_browse)
        Form.setTabOrder(self.radiance_browse, self.textbox_irradiance_path)
        Form.setTabOrder(self.textbox_irradiance_path, self.irradiance_browse)
        Form.setTabOrder(self.irradiance_browse, self.btn_export)
        Form.setTabOrder(self.btn_export, self.text_log)
        Form.setTabOrder(self.text_log, self.clear_log)

        self.btn_export.setStyleSheet("background-color: #3c6897")

        self.retranslateUi(Form)
        #self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Scene Export", None, -1))
        self.label_asset_folder_path.setText(QtWidgets.QApplication.translate("Form", "Asset folder path here", None, -1))
        self.folder_status.setText(QtWidgets.QApplication.translate("Form", "Folder status: Not set", None, -1))
        self.asset_path.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>assets folder root path for the project.</p></body></html>", None, -1))
        self.asset_path.setText(QtWidgets.QApplication.translate("Form", "asset folder path", None, -1))
        self.browse_asset_path.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Browse for the assets folder</p></body></html>", None, -1))
        self.browse_asset_path.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.label_scene_name.setText(QtWidgets.QApplication.translate("Form", "Scene name", None, -1))
        self.scene_name_input.setToolTip( QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Name of the scene</p></body></html>", None, -1))
        self.scene_name_input.setText(QtWidgets.QApplication.translate("Form", "scene", None, -1))
        self.radio_export_all.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Export all objects in the scene </p></body></html>",
                                                                          None, -1))
        self.radio_export_all.setText(QtWidgets.QApplication.translate("Form", "Export All", None, -1))
        self.radio_export_sel.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Export selected objects only</p></body></html>", None, -1))
        self.radio_export_sel.setText(QtWidgets.QApplication.translate("Form", "Export Selection", None, -1))
        self.check_export_animation.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Enable animation exporting</p></body></html>",  None, -1))
        self.check_export_animation.setText(QtWidgets.QApplication.translate("Form", "Export animation", None, -1))
        self.anim_range_label.setText(QtWidgets.QApplication.translate("Form", "Animation range", None, -1))
        self.anim_range_min.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Minimum keyframe range for the animation to be exported </p></body></html>", None, -1))
        self.anim_range_max.setToolTip(QtWidgets.QApplication.translate("Form","<html><head/><body><p>Maximum keyframe range for the animation to be exported </p></body></html>", None, -1))
        self.check_copy_textures.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Collect all textures outside of the assets folder and copy them to ./textures</p></body></html>",None, -1))
        self.check_copy_textures.setText(
            QtWidgets.QApplication.translate("Form", "Collect textures to asset folder", None, -1))
        self.keep_mat_paths.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Keep the original material paths instead of routing them to the asset paths.</p></body></html>", None, -1))
        self.keep_mat_paths.setText(QtWidgets.QApplication.translate("Form", "Keep original material paths", None, -1))
        self.label_export_scene_as.setText(QtWidgets.QApplication.translate("Form", "Export scene as", None, -1))
        self.radio_export_ptcloud.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Convert current scene to point cloud:</p><p>* Keeps object transforms and animations</p><p>* Exports each mesh instance to ./meshes folder</p><p>* Links mesh path back to the transform object</p></body></html>", None, -1))
        self.radio_export_ptcloud.setText(QtWidgets.QApplication.translate("Form", "Point cloud", None, -1))
        self.radio_export_fbx.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Export scene as a single FBX file</p></body></html>", None, -1))
        self.radio_export_fbx.setText(QtWidgets.QApplication.translate("Form", "Single FBX", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Extra file", None, -1))
        self.check_extra_ptcloud.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Export point coud data to the extra file</p></body></html>",  None, -1))
        self.check_extra_ptcloud.setText(QtWidgets.QApplication.translate("Form", "Point cloud data", None, -1))
        self.check_extra_occlusion.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Temporary feature waiting for engine updates - bake animated occlusion data. Needs a fixed camera animation to bake the occlusion to.</p></body></html>",  None, -1))
        self.check_extra_occlusion.setText(QtWidgets.QApplication.translate("Form", "Animated occlusion data", None, -1))
        self.active_camera_label.setText(QtWidgets.QApplication.translate("Form", "active camera:", None, -1))
        self.active_camera.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>The active camera to bake the occlusion data from.</p></body></html>",  None, -1))
        self.check_extra_lights.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Export light information to extra file</p></body></html>",  None, -1))
        self.check_extra_lights.setText(QtWidgets.QApplication.translate("Form", "Lights", None, -1))
        self.check_extra_special_mats.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Export special materials to extra file</p></body></html>",   None, -1))
        self.check_extra_special_mats.setText(QtWidgets.QApplication.translate("Form", "Special materials", None, -1))
        self.check_skybox.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Link skybox environment map path to extra file.</p></body></html>",  None, -1))
        self.check_skybox.setText(QtWidgets.QApplication.translate("Form", "Skybox", None, -1))
        self.check_skybox_radiance.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Link skybox radiance map path to extra file.</p></body></html>",  None, -1))
        self.check_skybox_radiance.setText(  QtWidgets.QApplication.translate("Form", "Separate radiance/irradiance", None, -1))
        self.skybox_envpath_label.setText(QtWidgets.QApplication.translate("Form", "Skybox environemnt path", None, -1))
        self.textbox_skybox_path.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Path to environment skybox texture.</p></body></html>", None, -1))
        self.textbox_skybox_path.setText(QtWidgets.QApplication.translate("Form", "skybox path", None, -1))
        self.skybox_browse.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Browse for environment skybox texture path.</p></body></html>", None, -1))
        self.skybox_browse.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.skybox_radiance_label.setText(QtWidgets.QApplication.translate("Form", "Skybox radiance path", None, -1))
        self.textbox_radiance_path.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Path to radiance skybox texture.</p></body></html>",  None, -1))
        self.textbox_radiance_path.setText(QtWidgets.QApplication.translate("Form", "radiance path", None, -1))
        self.radiance_browse.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Browse for radiance skybox texture path.</p></body></html>",  None, -1))
        self.radiance_browse.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.skybox_irradiance_label.setText(QtWidgets.QApplication.translate("Form", "Skybox irradiance path", None, -1))
        self.textbox_irradiance_path.setToolTip(QtWidgets.QApplication.translate("Form",  "<html><head/><body><p>Path to irradiance skybox texture.</p></body></html>",  None, -1))
        self.textbox_irradiance_path.setText(QtWidgets.QApplication.translate("Form", "irradiance path", None, -1))
        self.irradiance_browse.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>Browse for irradiance skybox texture path.</p></body></html>",  None, -1))
        self.irradiance_browse.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.btn_export.setText(QtWidgets.QApplication.translate("Form", "Export", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("Form", "Export", None, -1))
        self.clear_log.setText(QtWidgets.QApplication.translate("Form", "Clear", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log_tab), QtWidgets.QApplication.translate("Form", "Log", None, -1))
        self.about_text.setText(QtWidgets.QApplication.translate("Form", "by Laura K\n"
 "\n"
 "Experimental scene exporter for RS engine with option to export point clouds.\n"
 "\n"
 "What it does:\n"
 "* Create assets folder with default assets\n"
 "* Collect all textures into assets folder\n"
 "* Export scene into either a point cloud or a single FBX file\n"
 "\n"
 "Extra file generation\n"
 "* Generate baked occlusion animation (active camera needed)\n"
 "* Export light inforamtion (currently only supports point lights)\n"
 "* Special materials (not implemented yet)\n"
 "* Path to skybox + copy skybox to assets folder",
None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("Form", "About", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
